---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
  - name: "infoblox_hostname"
    prompt: "Enter infoblox hostname"
    private: no

  - name: "infoblox_username"
    prompt: "Enter infoblox username"
    private: no

  - name: "infoblox_password"
    prompt: "Enter infoblox password"
    private: yes

  - name: "infoblox_view"
    prompt: "Enter infoblox view name"
    private: no

  - name: "infoblox_name"
    prompt: "Enter name of infoblox record for test"
    private: no

  - name: "infoblox_ipv4addr"
    prompt: "Enter ip of infoblox record for test"
    private: no


  tasks:

###### A ########

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'a'
      infoblox_action: 'create'
    tags: a

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'a'
      infoblox_action: 'read'
    tags: a

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'a'
      infoblox_action: 'update'
    tags: a

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'a'
      infoblox_action: 'read'
    tags: a

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'a'
      infoblox_action: 'delete'
    tags: a

###### Host ########



  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'host'
      infoblox_action: 'create'
    tags: host

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'host'
      infoblox_action: 'read'
    tags: host

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'host'
      infoblox_action: 'update'
    tags: host

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'host'
      infoblox_action: 'read'
    tags: host

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'host'
      infoblox_action: 'delete'
    tags: host



###### CName ########



  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'cname'
      infoblox_action: 'create'
      infoblox_canonical: 'newhost.dhconsulting.ch'
      infoblox_name: 'newhostc.dhconsulting.ch'
    tags: cname

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'cname'
      infoblox_action: 'read'
      infoblox_name: 'newhostc.dhconsulting.ch'
    tags: cname

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'cname'
      infoblox_action: 'update'
      infoblox_canonical: 'newhost99.dhconsulting.ch'
      infoblox_name: 'newhostc.dhconsulting.ch'
    tags: cname

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'cname'
      infoblox_action: 'read'
      infoblox_name: 'newhostc.dhconsulting.ch'
    tags: cname

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'cname'
      infoblox_action: 'delete'
      infoblox_name: 'newhostc.dhconsulting.ch'
    tags: cname


###### PTR ########



  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'ptr'
      infoblox_action: 'create'
      infoblox_ipv4addr: '1.1.1.1'
    tags: ptr

  - import_role:
      name: damhau.infoblox
    vars:
      infoblox_recordtype: 'ptr'
      infoblox_action: 'read'
      infoblox_ipv4addr: '1.1.1.1'
    tags: ptr
